# Generated by Django 5.1.3 on 2024-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.BooleanField(default=False),
        ),
    ]
