# Generated by Django 5.1.3 on 2024-11-11 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('housing_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('townhouse', 'Таунхаус'), ('land', 'Земля'), ('duplex', 'Дуплекс'), ('studio', 'Студия'), ('penthouse', 'Пентхаус'), ('villa', 'Вилла'), ('cottage', 'Коттедж'), ('chalet', 'Шале')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
